name: Check the coding style using Black


on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'develop'
      - 'master'

jobs:
  Blacken:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Black
        run: pip install black==22.10.0

      - name: Run black
        run: black --check --diff .
